# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/generateweb ]
  pull_request:
    branches: [ feature/generateweb ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 首先生成拉取node文件
      - name: Node install
        uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
      
      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-
      
      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install vuepress

      # 运行构建脚本
      - name: Build VuePress site
        run: npm run docs:build

      # 进入到生成目录，并初始化git
      - name: init git
        run:
          cd docs/.vuepress/dist

          git init

          git add .

          git config --local user.email "821466754@qq.com"

          git config --local user.name "B15030328"

          git commit -m "generate web"
          
      
      # 提交到pages仓库
      - name: push to pages branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pages
          force: true
          directory: ./docs/.vuepress/dist